FROM node:14-alpine

WORKDIR /app

COPY . .
RUN npm install

ENV SECRET_JWT=jwtsecret
ENV ACCESS_TOKEN_EXPIRED=15m
ENV REFRESH_TOKEN_EXPIRED=7d

ENV PORT=3000

ENV DB_NAME_DEV=ptit
ENV DB_HOST_DEV=postgresql_db
ENV DB_USERNAME_DEV=admin
ENV DB_PASSWORD_DEV=admin1234
ENV DB_PORT=5432

ENV EMAIL_SERVICE=gmail
ENV EMAIL_ACCOUNT=***
ENV EMAIL_PASS=***

ENV HASH_SECRET=hash

ENV REDIS_HOST=redis_cache
ENV REDIS_PORT=6379

EXPOSE 3000

USER node

CMD [ "npm", "run", "start:dev" ]