version: '3.8'

services:
  postgresql_database:
    image: postgres:alpine
    container_name: postgresql_db
    environment:
      - POSTGRES_DB=ptit
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234

    ports:
      - '127.0.0.1:5432:5432'
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - '127.0.0.1:5050:80'
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin

  redis:
    image: redis:6.2-alpine
    container_name: redis_cache

    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - data-cache:/data
    restart: always

  backend:
    stdin_open: true
    tty: true
    container_name: backend_node_app
    build:
      context: ../
      dockerfile: dockerfile
    ports:
      - '127.0.0.1:3000:3000'
    restart: always
    volumes:
      - /app/node_modules
    depends_on:
      - postgresql_database
      - pgadmin
      - redis
volumes:
  database-data:
  pgadmin:
  data-cache:
